Implement email login and account creation
shockbytes/DanteX pull request #44
Opened 2022-11-22 06:49 UTC by lockieRichter

Implement the login screen for email and account creation bottom sheet. UI still needs polishing, but this works functionally for now and the layout/styling can be tweaked later.

Also missing a bunch of translations, unfortunately I can't speak a lot of German so will need @shockbytes to do the translations in another change. It's probably worth adding something to the README about the process for translations for other developers (for example at my work we don't use Google to do translations, we always make sure to get a fluent speaker of the language to do it).

This is a pretty massive change, so I might have missed some stuff!

**Enter email**
![image](https://user-images.githubusercontent.com/26178557/203243599-bed7f679-475d-46a1-a3b8-9ed1b0300ab3.png)

**Invalid email**
![image](https://user-images.githubusercontent.com/26178557/203243671-6b9047aa-9453-49e7-8920-228d57329400.png)

![image](https://user-images.githubusercontent.com/26178557/203243692-9efe1a1e-4611-4436-bada-6a8a42dcdf04.png)

**Email already in use**
![image](https://user-images.githubusercontent.com/26178557/203243762-1e5fade7-e695-478e-b854-6f148cd3d139.png)

**Existing user**
![image](https://user-images.githubusercontent.com/26178557/203243919-ffcad0aa-cdf9-4bfd-b092-9228f3d778d2.png)

**New user**
![image](https://user-images.githubusercontent.com/26178557/203243983-cd472bcb-489d-4360-969e-18d9e9fba2d6.png)

**Invalid password**
![image](https://user-images.githubusercontent.com/26178557/203244021-e0a12503-c1a8-475e-8f10-403a3883fc4b.png)

Closes 40

2022-11-24 19:59 UTC, shockbytes requested changes
Please update the german translations as well to this PR. I will then translate this directly on the PR.

2022-11-24 19:59 UTC, shockbytes commented on README.md
> +### String translations
👏

2022-11-24 19:59 UTC, shockbytes commented on README.md
> +All static text strings should be in the translations files located at `/lib/l10n`.
I think the folder is `/I10n` not `/l10n`

2022-11-24 19:59 UTC, shockbytes commented on lib/src/ui/login/login_page.dart
> +                        // onPressed: () => _bloc.loginWithEmail(),
Can be removed.

2022-11-24 19:59 UTC, shockbytes commented on lib/src/ui/login/login_page.dart
> +  late bool _loading;
Please use the `is` prefix => `_isLoading`

2022-11-24 20:00 UTC, shockbytes commented
@lockieRichter Please add the strings in the german file too, otherwise we might miss them. I think it's better to have all translations contained in such a PR.

2022-11-24 22:17 UTC, lockieRichter commented on README.md
> +All static text strings should be in the translations files located at `/lib/l10n`.
The translations are actually in the folder `/l10n`, are you thinking of `i18n`?

2022-11-24 22:17 UTC, lockieRichter commented on lib/src/ui/login/login_page.dart
> +                        // onPressed: () => _bloc.loginWithEmail(),
Good catch

2022-11-24 22:18 UTC, lockieRichter commented on lib/src/ui/login/login_page.dart
> +  late bool _loading;
Good catch.

2022-11-24 22:34 UTC, lockieRichter commented
@shockbytes can have a go at the translations, I don't speak much German unfortunately. Should I use Google translate or just put the translations in English?

2022-11-27 11:06 UTC, shockbytes commented on README.md
> +All static text strings should be in the translations files located at `/lib/l10n`.
yeah, sorry. `l10n` is right. I was indeed thinking about `i18n`. :D

2022-11-27 11:19 UTC, shockbytes commented
@lockieRichter I would suggest that you add the entries in the `app_de.arb` file too and use `"TODO"` placeholders for them. I will provide the german translation for it either by directly pushing a commit to the PR (as done now) or in one of my branches.

2022-11-27 11:21 UTC, shockbytes approved these changes

2022-11-27 11:47 UTC, merged