Implement anonymous account upgrade
shockbytes/DanteX pull request #46
Opened 2022-11-28 11:34 UTC by lockieRichter

Implements the basic logic and UI for upgrading an anonymous account to an email account.

- Creates a basic settings screen with an option for upgrading to email account for anonymous users.
- Re-uses the existing email bottom sheet for logging in.
- Adds modal for signing in as anonymous user.
- Adds modal for signing out as anonymous user.
- Replaces all instances of `Navigator.pop()` with `Get.back()`.

![image](https://user-images.githubusercontent.com/26178557/204265410-da728483-fd56-4ec4-9584-80bc67b015d2.png)

![image](https://user-images.githubusercontent.com/26178557/204264997-b544cfca-6923-472a-8e4c-3164bb9a51dc.png)

![image](https://user-images.githubusercontent.com/26178557/204265209-ac9a151d-1985-4e69-bd05-df0116b30f5a.png)

2022-11-29 17:43 UTC, shockbytes requested changes

2022-11-29 17:43 UTC, shockbytes commented on lib/src/data/authentication/firebase_authentication_repository.dart
> +      throw FirebaseAuthException(code: 'user-not-found');
Can you use a message here? Something like "Customer not logged in while trying to perform anonymous upgrade"

2022-11-29 17:43 UTC, shockbytes commented on lib/src/ui/settings/settings_app_bar.dart
> +class SettingsAppBar extends StatelessWidget implements PreferredSizeWidget {
It would be great if we're not creating the appBar all over again for each screen. Can we somehow create one that we can reuse for all the pages (except of the main page)?

2022-11-29 17:43 UTC, shockbytes commented on lib/src/ui/settings/settings_page.dart
> +                  future: _bloc.isAnonymousUser(),
I would not move this into the settings, I would rather place it in the bottomsheet on the main page (as on Dante for Android)

2022-11-29 22:04 UTC, lockieRichter commented on lib/src/data/authentication/firebase_authentication_repository.dart
> +      throw FirebaseAuthException(code: 'user-not-found');
Can do!

2022-11-29 22:05 UTC, lockieRichter commented on lib/src/data/authentication/firebase_authentication_repository.dart
> +      throw FirebaseAuthException(code: 'user-not-found');
Actually we should use the `message` field and keep the code the same.

2022-11-29 22:05 UTC, lockieRichter commented on lib/src/ui/settings/settings_app_bar.dart
> +class SettingsAppBar extends StatelessWidget implements PreferredSizeWidget {
Yes can have a go at this.

2022-11-29 22:13 UTC, lockieRichter commented on lib/src/ui/settings/settings_app_bar.dart
> +class SettingsAppBar extends StatelessWidget implements PreferredSizeWidget {
We should probably use the existing material app bar for all our components, including the main page app bar. Can do this in another ticket if needed.

2022-11-29 22:28 UTC, lockieRichter commented on lib/src/ui/settings/settings_page.dart
> +                  future: _bloc.isAnonymousUser(),
I can't see where this option is in my version of Dante for Android (even with an anonymous sign in), can you attach a screenshot of where this should be?

2022-11-30 10:44 UTC, lockieRichter commented on lib/src/ui/settings/settings_page.dart
> +                  future: _bloc.isAnonymousUser(),
ahh never mind, I think I understand what you mean now!

2022-12-03 16:01 UTC, shockbytes commented on lib/src/ui/settings/settings_app_bar.dart
> +class SettingsAppBar extends StatelessWidget implements PreferredSizeWidget {
Alright, let's do it in another ticket.

One thing I forgot to mention regarding the UI: I want to let it look "sort-of" native on iOS too. It should definitely not look like a material app. As you see, I already created the class `PlatformComponents` that gives us a small abstraction for the underlying platform components. Side note: Web and app will look similar.

2022-12-03 16:11 UTC, shockbytes approved these changes

2022-12-03 23:58 UTC, merged