Remove get x
shockbytes/DanteX pull request #50
Opened 2023-10-05 22:11 UTC by lockieRichter

* Removes the use of GetX in the app
* Replaces all instances of depedency injection using GetX with Riverpod
* Replaces all instances of navigation using GetX with Native flutter navigation

2023-10-05 22:12 UTC, lockieRichter commented
@shockbytes this is ready for review, one thing I am wondering is if we want to add the generated code to the `.gitignore`?

2023-10-06 06:27 UTC, shockbytes requested changes
Just left a couple of comments. I requested changes because the Action Checks are not working. Please fix the Android build.

2023-10-06 06:27 UTC, shockbytes commented on pubspec.yaml
> +  uuid: ^3.0.6
Why did you downgrade this one?

2023-10-06 06:27 UTC, shockbytes commented on lib/src/providers/authentication.dart
> +    throw UnimplementedError();
Why didn't you set up the database here but instead in main.dart?

2023-10-06 06:27 UTC, shockbytes commented on lib/main.dart
> +        databaseURL: 'https://dante-books.europe-west1.firebasedatabase.app/',
We might consider using the Firebase testing project in another ticket.

2023-10-06 06:27 UTC, shockbytes commented on lib/main.dart
> +            firebaseDatabaseProvider.overrideWithValue(firebaseDatabase),
Can you explain why we need this here?

2023-10-06 06:27 UTC, shockbytes commented on lib/main.dart
> +    }
Not sure why we need to intialize the Firebase App here again.

2023-10-06 06:29 UTC, shockbytes commented
> @shockbytes this is ready for review, one thing I am wondering is if we want to add the generated code to the `.gitignore`?

@lockieRichter I don't have a clear preference. Most of the time, I checked in generated code (like Hive). I would appreciate it if we could keep it out of the repository. However, that means we need to update our Github Actions to run the code generation step too, otherwise the builds will all fail.

2023-10-06 09:41 UTC, lockieRichter commented on pubspec.yaml
> +  uuid: ^3.0.6
There was a conflict in versions with Riverpod, downgrading was the only way I could get the dependencies working together.

2023-10-06 09:44 UTC, lockieRichter commented on lib/src/providers/authentication.dart
> +    throw UnimplementedError();
This is a sneaky trick to make our `firebaseDatabaseProvider` be a normal `Provider`, rather than a `FutureProvider` (if we were to use `await` here, we would need to mark is as `async` and Riverpod would convert it to a `FutureProvider` automatically). By doing this here, we can override with the value we get after `await`ing the initialisation in main.

If we don't do this, everywhere in our app that we use the `firebaseDatabaseProvider` will need to handle the case that it is uninitialised - this way we can ensure it always is by initialising in our main.

2023-10-06 09:45 UTC, lockieRichter commented on lib/main.dart
> +        databaseURL: 'https://dante-books.europe-west1.firebasedatabase.app/',
Yes that's a great idea, handling the different environments should be easy enough to do, but worth doing in another ticket for sure.

2023-10-06 09:46 UTC, lockieRichter commented on lib/main.dart
> +            firebaseDatabaseProvider.overrideWithValue(firebaseDatabase),
See my comment above on the [lib/src/providers/authentication.dart](https://github.com/shockbytes/DanteX/pull/50/files/6e84bb1b35011070abe552b6cabc1af5a949c493#diff-4bef2698b8a1153becc46ddc41ca71ed6a4a4092b15178e90f81b3430e805349) file.

2023-10-06 09:46 UTC, lockieRichter commented on lib/main.dart
> +    }
Good catch, this is a duplicate, will remove.

2023-10-06 09:50 UTC, lockieRichter commented on lib/src/providers/authentication.dart
> +    throw UnimplementedError();
Actually though the initialisation of the `FirebaseApp` is the async part, so I've extracted that to a single provider that we can now override.

2023-10-06 09:51 UTC, lockieRichter commented
> > @shockbytes this is ready for review, one thing I am wondering is if we want to add the generated code to the `.gitignore`?
> 
> @lockieRichter I don't have a clear preference. Most of the time, I checked in generated code (like Hive). I would appreciate it if we could keep it out of the repository. However, that means we need to update our Github Actions to run the code generation step too, otherwise the builds will all fail.

Ok cool, I'm going to add it to the `.gitignore` then.

2023-10-06 10:00 UTC, lockieRichter commented
@shockbytes ok so I've got the Android build working again and have updated the build pipeline to generate our code!!! Have a look and let me know 😎

2023-10-06 10:17 UTC, shockbytes approved these changes
:shipit:

2023-10-06 10:23 UTC, merged