Add Settings Screen
shockbytes/DanteX pull request #57
Opened 2023-10-11 20:50 UTC by shockbytes

### Overview

Add the settings screen and make the configuration available for other parts of the app.

### Screenshots

2023-10-17 22:20 UTC, lockieRichter requested changes
Good work, this is a big change but a really good one. Just a few comments to address.

2023-10-17 22:20 UTC, lockieRichter commented on lib/main.dart
> +Future<List<Override>> _initializeBlockingDependencies() async {
Nice

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/ui/settings/contributors_page.dart
> +  ContributorsPage({super.key});
Is there a way to make this const? Making widgets const allows the flutter renderer to skip re-rendering if it's not required and this widget will not change (no state changes anywhere)

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/providers/service.dart
> +    throw UnimplementedError();
Good use of this

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/ui/settings/contributors_page.dart
> +sealed class _ContributionType {}
What does this do? I haven't had to use the `sealed` keyword before 🤔

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/ui/settings/contributors_page.dart
> +          'https://discord.com/channels/824694597728993390/1037365721363136572',
I wonder if this and the contributor details should be stored as JSON config at the repository root. That way we wouldn't need to do code changes to update these things, which are possible to change?

Also might not be worth the effort if we think these things will be fairly static, will leave it up to you

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/ui/settings/settings_page.dart
> +    _repository = ref.read(settingsRepositoryProvider);
This is a bit of an anti patern with Riverpod. Rather than having a stateful widget with this stored in state, you should have a stateless widget and call `final repository = ref.watch(settingsRepositoryProvider)` at the top of the build method. When you want to check if tracking is enabled, you just call `repository. isTrackingEnabled()` throughout the widget. 

By watching the provider, the widget will rebuild if the provider changes and you get the benefit of a stateless widget. 

This also means that you don't need to do things like tracking state in the widget and the provider
```
 _repository.setSortingStrategy(selectedStrategy);
  setState(() {
    _selectedSortStrategy = selectedStrategy;
  });
```

2023-10-17 22:20 UTC, lockieRichter commented on lib/src/util/url_launcher.dart
> +class UrlLauncher {
There's no need for this to be a class. See https://dart.dev/tools/linter-rules/avoid_classes_with_only_static_members, but essentially the `launch` method can just be a method.

Also might be worth returning the result of `launchUrl(uri)`

2023-10-18 05:45 UTC, shockbytes commented on lib/src/providers/service.dart
> +    throw UnimplementedError();
Learned it from you ;)

2023-10-18 05:50 UTC, shockbytes commented on lib/src/ui/settings/contributors_page.dart
> +sealed class _ContributionType {}
A sealed class is, simply put, a enum with superpowers. Each subtype needs to be defined in the same file. So the Compiler can enforce exhaustive Switch cases without a need of a default branch. And you can have custom payloads in each class, which the compiler can resolve.

Strangely, in the switch statement, I needed to cast the subtype. Usually the compiler should be smart enough to do that for you.

2023-10-18 19:03 UTC, shockbytes commented on lib/src/ui/settings/contributors_page.dart
> +          'https://discord.com/channels/824694597728993390/1037365721363136572',
Will keep this config static. I had the same way of thinking as you. However, I don't assume that this will change very often.

2023-10-18 19:04 UTC, shockbytes commented on lib/src/ui/settings/contributors_page.dart
> +  ContributorsPage({super.key});
Made it `const` by making the `_contributors` readable through a `get` field.

2023-10-18 19:06 UTC, shockbytes commented on lib/src/ui/settings/settings_page.dart
> +    _repository = ref.read(settingsRepositoryProvider);
I do understand. However, it does not work for me with the booleans. The boolean switch is not updated (although the underlying values are changing).

2023-10-18 19:06 UTC, shockbytes commented on lib/src/ui/settings/settings_page.dart
> +    _repository = ref.read(settingsRepositoryProvider);
```dart
SettingsTile.switchTile(
                initialValue: repository.isRandomBooksEnabled(),
                activeSwitchColor: Theme.of(context).colorScheme.primary,
                onToggle: (bool newValue) {
                  repository.setIsRandomBooksEnabled(newValue);
                },
                title: Text(
                  AppLocalizations.of(context)!.settings_books_random_book,
                ),
                leading: const Icon(Icons.casino_outlined),
              ),
```
This code is not working for me. @lockieRichter can you please assist me on this?

2023-10-19 05:28 UTC, lockieRichter commented on lib/src/ui/settings/settings_page.dart
> +    _repository = ref.read(settingsRepositoryProvider);
I've just pushed something in my latest commit, it works, but I'm not sure if it's the best. It pretty much moves the handling of the double state that was in the widget before into a state notifier provider. I'm going to look arond (and maybe ask on the Riverpod repository) about what the best way to handle this is.

Will leave it up to you, we can either revert back to a stateful widget or leave it as I've done it until I can find a better solution.

2023-10-19 05:30 UTC, lockieRichter approved these changes

2023-10-19 06:23 UTC, merged